# Generated by Django 5.1.4 on 2025-01-30 17:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('oraculo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enquete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descricao', models.TextField()),
                ('data_inicio', models.DateTimeField()),
                ('data_fim', models.DateTimeField()),
                ('ativo', models.BooleanField(default=True)),
                ('opcao1', models.CharField(blank=True, default='', max_length=200)),
                ('opcao2', models.CharField(blank=True, default='', max_length=200)),
                ('opcao3', models.CharField(blank=True, default='', max_length=200)),
                ('opcao4', models.CharField(blank=True, default='', max_length=200)),
                ('created_dt', models.DateTimeField(auto_now_add=True)),
                ('updated_dt', models.DateTimeField(auto_now=True)),
                ('direcionado_a', models.ManyToManyField(related_name='enquetes', to='oraculo.cargo')),
                ('usuario', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='oraculo.user')),
            ],
        ),
        migrations.CreateModel(
            name='Resposta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resposta', models.CharField(max_length=255)),
                ('explicacao', models.TextField(blank=True, null=True)),
                ('enquete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respostas', to='enquete.enquete')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oraculo.user')),
            ],
            options={
                'verbose_name': 'Resposta',
                'verbose_name_plural': 'Respostas',
            },
        ),
    ]
