# Generated by Django 5.1.4 on 2025-01-30 22:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enquete', '0001_initial'),
        ('oraculo', '0002_alter_user_cargo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enquete',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oraculo.user'),
        ),
    ]
