# Generated by Django 5.1.4 on 2025-01-31 01:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enquete', '0002_alter_enquete_usuario'),
        ('oraculo', '0002_alter_user_cargo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enquete',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='oraculo.user'),
        ),
    ]
