# Generated by Django 5.1.4 on 2025-01-30 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oraculo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='cargo',
            field=models.CharField(choices=[('admin', 'Admin'), ('pastor', 'Pastor'), ('lider', 'Líder'), ('colaborador', 'Colaborador'), ('membro', 'Membro')], max_length=20),
        ),
    ]
